package com.masterplus.animals.core.domain.models

data class Animal(
    val id: Int?,
    val species: SpeciesModel,
    val images: List<SpeciesImageModel>,
    val physicalCharacteristics: String,
    val naturalHabitat: String,
    val ecosystem: String,
    val feedingHabits: String,
    val socialStructure: String,
    val reproductiveBehaviors: String,
    val developmentStages: String,
    val soundsProduced: String,
    val communicationMethods: String,
    val threats: String,
    val conservationEfforts: String,
    val culturalSignificance: String,
    val economicImportance: String,
    val environmentalAdaptations: String,
    val evolutionaryProcesses: String,
    val interestingBehaviors: String,
    val unknownFeatures: String,
    val funFacts: String,
    val size: String,
    val weight: String,
    val color: String,
    val habitat: String,
    val ecosystemCategory: String,
    val feeding: String,
    val socialStructureSimple: String,
    val reproductiveSimple: String,
    val developmentSimple: String,
    val sounds: String,
    val communication: String,
    val threatsSimple: String,
    val conservationStatus: String,
    val culturalSimple: String,
    val economicSimple: String,
    val adaptation: String,
    val evolution: String,
){
    val imageUrls get() = images.map { it.imageUrl }
}
