package com.masterplus.animals.core.shared_features.database.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

@Entity(
    tableName = "Animals",
    foreignKeys = [
        ForeignKey(
            entity = SpeciesEntity::class,
            parentColumns = ["id"],
            childColumns = ["species_id"],
        )
    ]
)
data class AnimalEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Int?,
    val species_id: Int,
    val physical_characteristics_en: String = "",
    val physical_characteristics_tr: String = "",
    val natural_habitat_en: String = "",
    val natural_habitat_tr: String = "",
    val ecosystem_en: String = "",
    val ecosystem_tr: String = "",
    val feeding_habits_en: String = "",
    val feeding_habits_tr: String = "",
    val social_structure_en: String = "",
    val social_structure_tr: String = "",
    val reproductive_behaviors_en: String = "",
    val reproductive_behaviors_tr: String = "",
    val development_stages_en: String = "",
    val development_stages_tr: String = "",
    val sounds_produced_en: String = "",
    val sounds_produced_tr: String = "",
    val communication_methods_en: String = "",
    val communication_methods_tr: String = "",
    val threats_en: String = "",
    val threats_tr: String = "",
    val conservation_efforts_en: String = "",
    val conservation_efforts_tr: String = "",
    val cultural_significance_en: String = "",
    val cultural_significance_tr: String = "",
    val economic_importance_en: String = "",
    val economic_importance_tr: String = "",
    val environmental_adaptations_en: String = "",
    val environmental_adaptations_tr: String = "",
    val evolutionary_processes_en: String = "",
    val evolutionary_processes_tr: String = "",
    val interesting_behaviors_en: String = "",
    val interesting_behaviors_tr: String = "",
    val fun_facts_en: String = "",
    val fun_facts_tr: String = "",
    val size_en: String = "",
    val size_tr: String = "",
    val weight_en: String = "",
    val weight_tr: String = "",
    val color_en: String = "",
    val color_tr: String = "",
    val habitat_en: String = "",
    val habitat_tr: String = "",
    val ecosystem_category_en: String = "",
    val ecosystem_category_tr: String = "",
    val feeding_en: String = "",
    val feeding_tr: String = "",
    val social_structure_simple_en: String = "",
    val social_structure_simple_tr: String = "",
    val reproductive_simple_en: String = "",
    val reproductive_simple_tr: String = "",
    val development_simple_en: String = "",
    val development_simple_tr: String = "",
    val sounds_en: String = "",
    val sounds_tr: String = "",
    val communication_en: String = "",
    val communication_tr: String = "",
    val threats_simple_en: String = "",
    val threats_simple_tr: String = "",
    val conservation_status_en: String = "",
    val conservation_status_tr: String = "",
    val cultural_simple_en: String = "",
    val cultural_simple_tr: String = "",
    val economic_simple_en: String = "",
    val economic_simple_tr: String = "",
    val adaptation_en: String = "",
    val adaptation_tr: String = "",
    val evolution_en: String = "",
    val evolution_tr: String = "",
    val comparative_analysis_tr: String = "",
    val comparative_analysis_en: String = "",
    val ethological_insights_tr: String = "",
    val ethological_insights_en: String = "",
    val modern_day_perception_tr: String = "",
    val modern_day_perception_en: String = "",
    val conservation_challenges_tr: String = "",
    val conservation_challenges_en: String = "",
)
